vim.cmd [[packadd packer.nvim]]
require('impatient')
require('plugins')
require('setup')
require('settings')
require('maps')
require('lsp')
require('treesitter')
require('nvimtree')
require('highlight')
